# Pre-commit hooks configuration
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      # Run the linter
      - id: ruff
        name: ruff (lint)
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
        name: ruff (format)

  # MyPy type checking disabled in pre-commit due to module resolution conflicts
  # Use 'make type-check' for proper type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       name: mypy (type check)
  #       args: [--ignore-missing-imports, --no-strict-optional, --disable-error-code=import-untyped, --explicit-package-bases]
  #       exclude: ^test/
