name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Update dependencies
      run: |
        uv lock --upgrade
        uv sync --extra dev --extra test

    - name: Run tests to ensure updates don't break anything
      run: |
        source .venv/bin/activate
        uv run pytest -v

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "Automated dependency updates"
        body: |
          This PR contains automated dependency updates.

          - Dependencies have been updated to their latest compatible versions
          - All tests pass with the updated dependencies
          - Please review the changes and merge if everything looks good

          Generated by GitHub Actions.
        branch: dependency-updates
        delete-branch: true
